//
//  constants.h
//  DigiCoin
//
//  Created by Nadaf, Ramin on 7/1/18.
//  Copyright © 2018 Nadaf, Ramin. All rights reserved.
//

#ifndef constants_h
#define constants_h

#define GLOBAL_SLEEP_TIME 0.25

#define DEFAULT_BORDER_RADIUS 6

#define DATABASE_HYBRID 1
#define DATABASE_MOVIE 2
#define DATABASE_MUSIC 3

#define STANDARD_GREEN_COLOR [UIColor colorWithRed:79.0/255.0 green:161.0/255.0 blue:81.0/255.0 alpha:1]
#define STANDARD_RED_COLOR [UIColor redColor]
#define STANDARD_BLUE_COLOR [UIColor colorWithRed:0.25 green:0.48 blue:0.698 alpha:1]
#define SATR_RATING_COLOR [UIColor colorWithRed:255/255.0f green:147/255.0f blue:29/255.0 alpha:1.0]

#define ASSET_TYPE_MOVIE 0
#define ASSET_TYPE_TVSHOW 1
#define ASSET_TYPE_MUSIC 2
#define ASSET_TYPE_GAME 3
#define ASSET_TYPE_BOOK 4

#define ASSET_CATEGORY_MYASSET 0
#define ASSET_CATEGORY_TOPASSET 1
#define ASSET_CATEGORY_SUGGESTION 2
#define ASSET_CATEGORY_TRENDING 3

//#define TRADE_CATEGORY_SELL 1
//#define TRADE_CATEGORY_BUY 2

#define ASSET_STATUS_IN_MARKETPLACE 1
#define ASSET_STATUS_AVAILABLE_TOTRADE 2
#define ASSET_STATUS_UNAVAILABLE_TOTRADE 3

#define APP_STATUS_MOVIE 1
#define APP_STATUS_MUSIC 2
#define APP_STATUS_HYBRID 3

#define TRANSACTION_STATUS_UNAVAILABLE -1
#define TRANSACTION_STATUS_BUY 1
#define TRANSACTION_STATUS_SELL 2
#define TRANSACTION_STATUS_IN_MARKET 3
#define TRANSACTION_STATUS_SOLD 4

#define TRADE_BUTTON_SELL 1
#define TRADE_BUTTON_BUY 2

#define PUBLISHER_ID_DISNEY 1
#define PUBLISHER_ID_DREAMWORKS 2
#define PUBLISHER_ID_MGM 3
#define PUBLISHER_ID_NBC 4
#define PUBLISHER_ID_WB 5
#define PUBLISHER_ID_UNIVERSAL_MUSIC 6
#define PUBLISHER_ID_PARAMOUNT 8
#define PUBLISHER_ID_UNIVERSAL 9
#define PUBLISHER_ID_SONY 10

#define PLATFORM_ID_AMAZON 1
#define PLATFORM_ID_HBO 2
#define PLATFORM_ID_HULU 3
#define PLATFORM_ID_ITUNES 4
#define PLATFORM_ID_NETFLIX 5
#define PLATFORM_ID_SHOWTIME 6
#define PLATFORM_ID_VIMEO 7
#define PLATFORM_ID_VIRGIN 8
#define PLATFORM_ID_VUDU 9
#define PLATFORM_ID_WALMART 10


#define ACCESSORY_DISCLOSURE_ICON_AVAILABLE "accDisclosure.png"
#define ACCESSORY_DISCLOSURE_ICON_UNAVAILABLE "checkbox-uncheck.PNG"

#define PUSH_ASSET_TRANSACTION_FROM_PUBLISHER_CONTRACT_VIEW 1
#define PUSH_ASSET_TRANSACTION_FROM_MOVIE_VIEW 2
#define PUSH_ASSET_TRANSACTION_FROM_ASSETS_VIEW 3



#endif /* constants_h */
